ALTER TABLE EmpComponents ALTER COLUMN DRPercentage Decimal(20,3)
ALTER TABLE BIMonthlyBonusInfo ALTER COLUMN Percentage Decimal(20,3)
ALTER TABLE TGPCustomerInfo ALTER COLUMN Percentage Decimal(20,3)
ALTER TABLE TenureBonus ALTER COLUMN Percentage Decimal(20,3)
-----drop querry for userdefined tables
ALTER TABLE EmpComponents ALTER COLUMN MonthAmount Decimal(20,3)
ALTER TABLE EmpComponents ALTER COLUMN DDAmount Decimal(20,3)
ALTER TABLE CommissionComponents ALTER COLUMN AmountofSale Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN CostofGoods Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN DollarVolume Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN BaseCommission Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN LeaseCommission Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN ServiceCommission Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN TravelCommission Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN CashCommission Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN SpecialCommission Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN TradeIn Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN TipLeadAmount Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN PositiveAdjustments Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN NegativeAdjustments Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN CompanyContribution Decimal(20, 3)
ALTER TABLE CommissionComponents ALTER COLUMN TotalCEarned Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN TotalCommission Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN DrawPaid Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN DrawRecovered Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN CommissionDue Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN Salary Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN BimonthlyBonus Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN TenureBonus Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN TotalEarnings Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN DrawAmount Decimal(20,3)
ALTER TABLE ReportDetails ALTER COLUMN RecoverablePercentage Decimal(20, 3)
ALTER TABLE ReportDetails ALTER COLUMN DrawDificit Decimal(20, 3)